### ISSUE TITLE
chown: cannot access `/etc/docker': No such file or directory during Travis job

### ISSUE THREAD

**Issue by d3ming** [moul/travis-docker#28]
Just trying this out and my Travis job fails on the install step:

```
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:
  sudo usermod -aG docker travis
Remember that you will have to log out and back in for this to take effect!
+sudo usermod -aG docker travis
+sudo chown -R travis /etc/docker
chown: cannot access `/etc/docker': No such file or directory
The command "curl -sLo - http://j.mp/install-travis-docker | sh -xe" failed and exited with 1 during .
Your build has been stopped.
```

Here's my full .travis.yml:

```
# See documentation at: http://docs.travis-ci.com/user/customizing-the-build/
# sudo: true is needed for https://github.com/moul/travis-docker
sudo: true

env:
  global:
    - UML_DOCKERCOMPOSE=1

language: php

before_install:
  - npm install
  - ./vagrant/scripts/bootstrap.sh

install:
  # docker stuff: https://github.com/moul/travis-docker
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe
  # PL stuff
  - grunt

before_script:
  - ./run 'docker build -t test . && docker run test'

script:
  - npm test
  # spin up docker
  - ./run docker-compose up
```

**Comment by moul** [comment]
I think this is due to the new way to install docker, see http://blog.docker.com/2015/07/new-apt-and-yum-repos/.

I will check

**Comment by moul** [comment]
Fixed with latest [stable release](https://github.com/moul/travis-docker/releases/tag/v1.1.0)

Try to just re-run the test :)

**Comment by d3ming** [comment]
Worked like a charm, thanks for the quick turnaround!

One followup question/suggestion is that... can we make the variable `BRANCH` named more specifically like 'TRAVIS_DOCKER_BRANCH'?  Because it's described in the project's .travis.yml file, a generic name like `BRANCH` can be confusing.

**Comment by d3ming** [comment]
Oh actually, the install worked but the test test for the container still failed with an error about being out of space: `ERRO[0071] Error from V2 registry: Untar re-exec error: exit status 1: output: write /usr/share/locale/ja/LC_MESSAGES/apt.mo: no space left on device`

Full logs:

```
$ ./run 'docker build -t test . && docker run test'
+sudo /home/travis/build/d3ming/placelocal/linux quiet mem=2G rootfstype=hostfs rw eth0=slirp,,/usr/bin/slirp-fullbolt init=/home/travis/build/d3ming/placelocal/linux-init WORKDIR=/home/travis/build/d3ming/placelocal UMLDIR=/home/travis/build/d3ming/placelocal QUIET=0 DOCKER_STORAGE_DRIVER=aufs DOCKER_BACKEND_FS=tmpfs
Core dump limits :
    soft - 0
    hard - NONE
Checking that ptrace can change system call numbers...OK
Checking syscall emulation patch for ptrace...OK
Checking advanced syscall emulation patch for ptrace...OK
Checking for tmpfs mount on /dev/shm...nothing mounted on /dev/shm
Checking PROT_EXEC mmap in /tmp/...OK
Checking for the skas3 patch in the host:
  - /proc/mm...not found: No such file or directory
  - PTRACE_FAULTINFO...not found
  - PTRACE_LDT...not found
UML running in SKAS0 mode
Adding 25161728 bytes to physical memory to account for exec-shield gap
+ rm -f /home/travis/build/d3ming/placelocal/.exit_code
++ uname -r
+ sudo mkdir -p /lib/modules/3.8.13.4
sudo: unable to resolve host (none)
+ sudo depmod -a
+ trap save_and_shutdown EXIT SIGINT SIGTERM
+ cd /home/travis/build/d3ming/placelocal
+ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ mount -t proc none /proc
+ mkdir -p /dev/pts
+ mount -t devpts none /dev/pts
+ mkdir -p /dev/shm
+ mount -t tmpfs none /dev/shm
+ mount -t sysfs none /sys
+ mkdir -p /var/run
+ mount -t tmpfs none /var/run
+ cgroups-mount
+ case ${DOCKER_BACKEND_FS} in
+ mount -t tmpfs none /var/lib/docker
+ echo 1
+ ip addr add 127.0.0.1 dev lo
+ ip link set lo up
+ ip addr add 10.1.1.1/24 dev eth0
+ ip link set eth0 up
Slirp v1.0.17 (BETA) FULL_BOLT
Copyright (c) 1995,1996 Danny Gasparovski and others.
All rights reserved.
This program is copyrighted, free software.
Please read the file COPYRIGHT that came with the Slirp
package for the terms and conditions of the copyright.
IP address of Slirp host: 127.0.0.1
IP address of your DNS(s): 8.8.8.8, 8.8.4.4, 208.67.222.222, (more)
Your address is 10.0.2.15
(or anything else you want)
Type five zeroes (0) to exit.
[autodetect SLIP/CSLIP, MTU 1500, MRU 1500]
SLiRP Ready ...
+ ip route add default via 10.1.1.254
+ mkdir -p /run/resolvconf
+ echo 'nameserver 8.8.8.8'
+ mount --bind /run/resolvconf/resolv.conf /etc/resolv.conf
+ '[' 0 -eq 0 ']'
+ '[' -e /var/run/docker.sock ']'
+ sleep 0.1
+ docker --storage-driver=aufs -d -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375
+ '[' -e /var/run/docker.sock ']'
+ sleep 0.1
+ '[' -e /var/run/docker.sock ']'
+ sleep 0.1
WARN[0000] You are running linux kernel version 3.8.13.4, which might be unstable running docker. Please upgrade your kernel to 3.10.0. 
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
WARN[0000] /!\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\ 
INFO[0000] Listening for HTTP on tcp (0.0.0.0:2375)     
WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1 
+ '[' -e /var/run/docker.sock ']'
+ '[' 0 -eq 0 ']'
+ echo '+ docker info'
+ docker info
+ docker info
INFO[0001] Loading containers: start.                   
INFO[0001] Loading containers: done.                    
INFO[0001] Daemon has completed initialization          
INFO[0001] Docker daemon                                 commit=786b29d execdriver=native-0.2 graphdriver=aufs version=1.7.1
INFO[0001] GET /v1.19/info                              
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: tmpfs
 Dirs: 0
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.8.13.4
Operating System: <unknown>
CPUs: 1
Total Memory: 1.926 GiB
Name: (none)
ID: RJIS:6NDF:RYHF:MZDT:AYYL:IQHG:ES6P:7IUU:MKY7:ZYSP:3SE4:QCQB
+ echo '+ docker version'
+ docker version
+ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
INFO[0001] GET /v1.19/version                           
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
+ . /home/travis/build/d3ming/placelocal/.envp
++ export BRANCH=stable
++ BRANCH=stable
++ export CI=true
++ CI=true
++ export COMPOSER_NO_INTERACTION=1
++ COMPOSER_NO_INTERACTION=1
++ export CONTINUOUS_INTEGRATION=true
++ CONTINUOUS_INTEGRATION=true
++ export DEBIAN_FRONTEND=noninteractive
++ DEBIAN_FRONTEND=noninteractive
++ export GEM_HOME=/home/travis/.rvm/gems/ruby-1.9.3-p551
++ GEM_HOME=/home/travis/.rvm/gems/ruby-1.9.3-p551
++ export GEM_PATH=/home/travis/.rvm/gems/ruby-1.9.3-p551:/home/travis/.rvm/gems/ruby-1.9.3-p551@global
++ GEM_PATH=/home/travis/.rvm/gems/ruby-1.9.3-p551:/home/travis/.rvm/gems/ruby-1.9.3-p551@global
++ export GIT_ASKPASS=echo
++ GIT_ASKPASS=echo
++ export GOROOT=/home/travis/.gimme/versions/go1.4.1.linux.amd64
++ GOROOT=/home/travis/.gimme/versions/go1.4.1.linux.amd64
++ export HAS_ANTARES_THREE_LITTLE_FRONZIES_BADGE=true
++ HAS_ANTARES_THREE_LITTLE_FRONZIES_BADGE=true
++ export HAS_JOSH_K_SEAL_OF_APPROVAL=true
++ HAS_JOSH_K_SEAL_OF_APPROVAL=true
++ export HOME=/home/travis
++ HOME=/home/travis
++ export IRBRC=/home/travis/.rvm/rubies/ruby-1.9.3-p551/.irbrc
++ IRBRC=/home/travis/.rvm/rubies/ruby-1.9.3-p551/.irbrc
++ export JAVA_HOME=/usr/lib/jvm/java-7-oracle
++ JAVA_HOME=/usr/lib/jvm/java-7-oracle
++ export 'JRUBY_OPTS=--client -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -Xcext.enabled=false -J-Xss2m -Xcompile.invokedynamic=false'
++ JRUBY_OPTS='--client -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -Xcext.enabled=false -J-Xss2m -Xcompile.invokedynamic=false'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ export LC_ALL=en_US.UTF-8
++ LC_ALL=en_US.UTF-8
++ export LC_CTYPE=en_US.UTF-8
++ LC_CTYPE=en_US.UTF-8
++ export LOGNAME=travis
++ LOGNAME=travis
++ export MAIL=/var/mail/travis
++ MAIL=/var/mail/travis
++ export MANPATH=/home/travis/.nvm/v0.10.36/share/man:/usr/local/clang-3.4/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
++ MANPATH=/home/travis/.nvm/v0.10.36/share/man:/usr/local/clang-3.4/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
++ export MERB_ENV=test
++ MERB_ENV=test
++ export MY_RUBY_HOME=/home/travis/.rvm/rubies/ruby-1.9.3-p551
++ MY_RUBY_HOME=/home/travis/.rvm/rubies/ruby-1.9.3-p551
++ export NVM_BIN=/home/travis/.nvm/v0.10.36/bin
++ NVM_BIN=/home/travis/.nvm/v0.10.36/bin
++ export NVM_DIR=/home/travis/.nvm
++ NVM_DIR=/home/travis/.nvm
++ export NVM_IOJS_ORG_MIRROR=https://iojs.org/dist
++ NVM_IOJS_ORG_MIRROR=https://iojs.org/dist
++ export NVM_IOJS_ORG_VERSION_LISTING=https://iojs.org/dist/index.tab
++ NVM_IOJS_ORG_VERSION_LISTING=https://iojs.org/dist/index.tab
++ export NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist
++ NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist
++ export NVM_PATH=/home/travis/.nvm/v0.10.36/lib/node
++ NVM_PATH=/home/travis/.nvm/v0.10.36/lib/node
++ export OLDPWD=/home/travis/build/d3ming/placelocal
++ OLDPWD=/home/travis/build/d3ming/placelocal
++ export PATH=/home/travis/bin:/home/travis/.local/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/home/travis/.phpenv/shims:/usr/local/phantomjs/bin:/home/travis/.nvm/v0.10.36/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/home/travis/.phpenv/shims:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/home/travis/.rvm/gems/ruby-1.9.3-p551/bin:/home/travis/.rvm/gems/ruby-1.9.3-p551@global/bin:/home/travis/.rvm/rubies/ruby-1.9.3-p551/bin:/home/travis/.phpenv/shims:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.phpenv/bin:/home/travis/.rvm/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin
++ PATH=/home/travis/bin:/home/travis/.local/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/home/travis/.phpenv/shims:/usr/local/phantomjs/bin:/home/travis/.nvm/v0.10.36/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/home/travis/.phpenv/shims:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/home/travis/.rvm/gems/ruby-1.9.3-p551/bin:/home/travis/.rvm/gems/ruby-1.9.3-p551@global/bin:/home/travis/.rvm/rubies/ruby-1.9.3-p551/bin:/home/travis/.phpenv/shims:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.phpenv/bin:/home/travis/.rvm/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin
++ export PS4=+
++ PS4=+
++export PWD=/home/travis/build/d3ming/placelocal
++PWD=/home/travis/build/d3ming/placelocal
++export RACK_ENV=test
++RACK_ENV=test
++export RAILS_ENV=test
++RAILS_ENV=test
++export RBENV_SHELL=bash
++RBENV_SHELL=bash
++export RUBY_VERSION=ruby-1.9.3-p551
++RUBY_VERSION=ruby-1.9.3-p551
++export SHELL=/bin/bash
++SHELL=/bin/bash
++export SHLVL=3
++SHLVL=3
++export SSH_AGENT_PID=2531
++SSH_AGENT_PID=2531
++export SSH_AUTH_SOCK=/tmp/ssh-NEBrqJQt2530/agent.2530
++SSH_AUTH_SOCK=/tmp/ssh-NEBrqJQt2530/agent.2530
++export 'SSH_CLIENT=2607:f700:8001:13f:2c1c:fd3e:397d:8d02 34126 22'
++SSH_CLIENT='2607:f700:8001:13f:2c1c:fd3e:397d:8d02 34126 22'
++export 'SSH_CONNECTION=2607:f700:8001:13f:2c1c:fd3e:397d:8d02 34126 2607:f700:8001:134:42ca:ce02:ac84:badf 22'
++SSH_CONNECTION='2607:f700:8001:13f:2c1c:fd3e:397d:8d02 34126 2607:f700:8001:134:42ca:ce02:ac84:badf 22'
++export SSH_TTY=/dev/pts/0
++SSH_TTY=/dev/pts/0
++export TERM=xterm
++TERM=xterm
++export TRAVIS=true
++TRAVIS=true
++export TRAVIS_BRANCH=hosted-ci
++TRAVIS_BRANCH=hosted-ci
++export TRAVIS_BUILD_DIR=/home/travis/build/d3ming/placelocal
++TRAVIS_BUILD_DIR=/home/travis/build/d3ming/placelocal
++export TRAVIS_BUILD_ID=14132107
++TRAVIS_BUILD_ID=14132107
++export TRAVIS_BUILD_NUMBER=10
++TRAVIS_BUILD_NUMBER=10
++export TRAVIS_COMMIT=c72121b293778b358b9d3bdee06d198c8d274b5a
++TRAVIS_COMMIT=c72121b293778b358b9d3bdee06d198c8d274b5a
++export TRAVIS_COMMIT_RANGE=46d33fa46e06...c72121b29377
++TRAVIS_COMMIT_RANGE=46d33fa46e06...c72121b29377
++export TRAVIS_JOB_ID=21237143
++TRAVIS_JOB_ID=21237143
++export TRAVIS_JOB_NUMBER=10.1
++TRAVIS_JOB_NUMBER=10.1
++export TRAVIS_LANGUAGE=php
++TRAVIS_LANGUAGE=php
++export TRAVIS_OS_NAME=linux
++TRAVIS_OS_NAME=linux
++export TRAVIS_PHP_VERSION=5.5
++TRAVIS_PHP_VERSION=5.5
++export TRAVIS_PULL_REQUEST=false
++TRAVIS_PULL_REQUEST=false
++export TRAVIS_REPO_SLUG=d3ming/placelocal
++TRAVIS_REPO_SLUG=d3ming/placelocal
++export TRAVIS_SECURE_ENV_VARS=false
++TRAVIS_SECURE_ENV_VARS=false
++export TRAVIS_TAG=
++TRAVIS_TAG=
++export UML_DOCKERCOMPOSE=1
++UML_DOCKERCOMPOSE=1
++export USER=travis
++USER=travis
++export _=./run
++_=./run
++export _system_arch=x86_64
++_system_arch=x86_64
++export _system_name=Ubuntu
++_system_name=Ubuntu
++export _system_type=Linux
++_system_type=Linux
++export _system_version=12.04
++_system_version=12.04
++export rvm_autoupdate_flag=0
++rvm_autoupdate_flag=0
++export rvm_bin_path=/home/travis/.rvm/bin
++rvm_bin_path=/home/travis/.rvm/bin
++export rvm_loaded_flag=1
++rvm_loaded_flag=1
++export rvm_max_time_flag=5
++rvm_max_time_flag=5
++export rvm_path=/home/travis/.rvm
++rvm_path=/home/travis/.rvm
++export rvm_prefix=/home/travis
++rvm_prefix=/home/travis
++export rvm_project_rvmrc=0
++rvm_project_rvmrc=0
++export rvm_silence_path_mismatch_check_flag=1
++rvm_silence_path_mismatch_check_flag=1
++export rvm_stored_umask=0002
++rvm_stored_umask=0002
++export rvm_user_install_flag=1
++rvm_user_install_flag=1
++export 'rvm_version=1.26.8 (1.26.8)'
++rvm_version='1.26.8 (1.26.8)'
++export 'rvm_with_default_gems=rake=~>10.2.2 bundler=~>1.6.0'
++rvm_with_default_gems='rake=~>10.2.2 bundler=~>1.6.0'
++export rvm_without_gems=rubygems-bundler
++rvm_without_gems=rubygems-bundler
++cat /home/travis/build/d3ming/placelocal/.command
+command='docker build -t test . && docker run test'
+set +e
+/bin/bash -xec 'docker build -t test . && docker run test'
+docker build -t test .
INFO[0009] POST /v1.19/build?cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=test 
Sending build context to Docker daemon 827.6 MB
Sending build context to Docker daemon 
Step 0 : FROM debian:jessie
INFO[0059] Image manifest for debian:jessie has been verified 
jessie: Pulling from debian
ERRO[0071] Error from V2 registry: Untar re-exec error: exit status 1: output: write /usr/share/locale/ja/LC_MESSAGES/apt.mo: no space left on device 
Pulling repository debian
age for debian:jessie
 ---> 9a61b6b1315e
Step 1 : WORKDIR /var/www
 ---> Running in 9d01bb0dc05e
 ---> 77731c907a0b
Removing intermediate container 9d01bb0dc05e
Step 2 : COPY . /var/www/
Untar re-exec error: exit status 1: output: write /linux: no space left on device
+echo 1
+save_and_shutdown
+'[' '!' -f /home/travis/build/d3ming/placelocal/.exit_code ']'
+set +e
++jobs -p
+kill -9 104
+halt -f
[   96.290000] System halted.
The command "./run 'docker build -t test . && docker run test'" failed and exited with 1 during .
```

**Comment by orius123** [comment]
did you try using `host` instead of `tmpfs`?
look a the https://github.com/moul/travis-docker-example for examples

**Comment by d3ming** [comment]
Ah yes, that did it.  Thanks!

**Comment by moul** [comment]
@d3ming, I created a dedicated issue about the variable naming (#30)

---

@orius123 thanks for the help. I will see to change the default configuration for the next stable release
